FROM ubuntu:latest

RUN apt-get update && apt-get install -y jq openssl curl iputils-ping curl mosquitto-clients

COPY ./publisher/ /publisher/

COPY ./ca-certs/ /publisher/ca-certs/

# Create a directory to store custom certificates
RUN mkdir -p /usr/local/share/ca-certificates

# Copy the custom certificate to the container
RUN cp /publisher/ca-certs/* /usr/local/share/ca-certificates/

RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates

WORKDIR /publisher

RUN chmod +x req_crt.sh

RUN chown root:root /publisher/req_crt.sh

ENTRYPOINT ["/bin/bash", "/publisher/req_crt.sh"]


