FROM eclipse-mosquitto:latest

COPY ./mosquitto/ /mosquitto/

COPY ./ca-certs/ /mosquitto/ca-certs/

#to trust the self-signed certificate CA
RUN cp /mosquitto/ca-certs/* /usr/local/share/ca-certificates/

#update the trust store certificates
RUN update-ca-certificates



